
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8150
#  jpa:
#    properties:
#      hibernate.show-sql: true
#      hibernate.format_sql: true
#      hibernate.use_sql_comments: true
#      hibernate.jdbc.lob.non_contextual_creation: true
#      hibernate.jdbc.diralect: org.hibernate.dialect.PostgreSQL95Dialect
#    hibernate:
#      # ddl-auto 설정
#      # none: 기본 값이며 아무 일도 일어나지 않는다.
#      # create: 데이터베이스를 drop 한 후, 데이터베이스를 새로 생성한다.
#      # create-drop: SessionFactory가 시작될 때 스키마를 drop하고 재생성하며, SessionFactory가 종료될 때도 스키마를 drop 한다.
#      # validate: 데이터베이스 스키마를 검증 한다.
#      # update: 데이터베이스 스키마를 갱신 한다.
#      ddl-auto: none
#    open-in-view: true
#    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#    database: postgresql